name: Rosetta 2 on ARM macOS Action Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    # Run on macOS 15 (arm64) GitHub Action Runner
    runs-on: macos-15
    steps:
      - name: Install Rosetta 2
        run: |
          softwareupdate --install-rosetta --agree-to-license
      - name: Prepare Shell arch test script
        run: |
          echo 'arch' > show-arch.sh
      - name: Test to x86_64 Shell
        # This should output "i386"
        run: |
          /usr/bin/arch -x86_64 /bin/zsh show-arch.sh
      - name: Install x86_64 Homebrew
        run: |
          /usr/bin/arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install LLVM from x86_64 Homebrew
        continue-on-error: true # Allow this as Python (installed as LLVM dependency) should fail when Homebrew links it.
        run: |
          /usr/bin/arch -x86_64 /usr/local/bin/brew install llvm
      - name: Force link Python installed from x86_64 Homebrew
        run: |
          /usr/bin/arch -x86_64 /usr/local/bin/brew link --overwrite python3
