name: Test Setup Shell Environment Variable

on:
  push:
    paths:
      - '.github/workflows/setup-shell-env.yml'
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-15
    steps:
      - name: Setup EXPORT Script
        run: |
          echo 'export TEST="Hello, GitHub!"' > set-env.sh
          echo 'echo \'TEST="Hello, GitHub!"\'' >> $GITHUB_ENV
      - name: Run the EXPORT Script
        run: |
          /bin/zsh set-env.sh
      - name: Check Environment Variable
        run: |
          echo $TEST
